version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    # configura o volume do serviço do postgres
    volumes:
      # para salvar no volume do Docker
      - postgres_data:/var/lib/postgresql/data
    # configura as variáveis de ambiente do serviço do postgres
    environment:
      # Define a senha do usuario postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - network_swarm_public
    # define o modo de deploy do container
    deploy:
      # configura o modo de deploy do serviço do postgres
      mode: replicated
      # configura o numero de replicas do serviço do postgres (1 é o padrão)
      replicas: 1
      # Define a estratégia de deploy do serviço
      placement:
        constraints:
          - node.role == manager

volumes:
  postgres_data:
    external: true
    name: postgres_data

networks:
  network_swarm_public:
    external: true